--
-- Dados iniciais do Nou-Rau: formatos, categorias, tipos de informação, ODS
--

SELECT SETVAL('nr_category_seq','0');
SELECT SETVAL('nr_document_seq','0');
SELECT SETVAL('nr_format_seq',  '0');
SELECT SETVAL('type_information_seq', '68');
SELECT SETVAL('supplementary_files_seq', '0');

-- Categorias de formato
INSERT INTO nr_category VALUES ('1','Text',       'Any simple text: ASCII, HTML, XML, ...',      '0');
INSERT INTO nr_category VALUES ('2','Image',      'Any image type: GIF, JPG, PNG, ...',          '0');
INSERT INTO nr_category VALUES ('3','Audio',      'Any audio type: MIDI, MP3, WAV, ...',         '0');
INSERT INTO nr_category VALUES ('4','Video',      'Any video type: MPEG, Quicktime, ...',        '0');
INSERT INTO nr_category VALUES ('5','Model',      'Any 3D type: VRML',                           '0');
INSERT INTO nr_category VALUES ('6','Application','Any application type: PS, PDF, DOC, ZIP, ...','0');
INSERT INTO nr_category VALUES ('7','Generic',    'Any document type',                           '0');

-- Mapeamento categoria-formato
INSERT INTO nr_category_format VALUES ('1','1');
INSERT INTO nr_category_format VALUES ('2','2');
INSERT INTO nr_category_format VALUES ('3','3');
INSERT INTO nr_category_format VALUES ('4','4');
INSERT INTO nr_category_format VALUES ('5','5');
INSERT INTO nr_category_format VALUES ('6','6');
INSERT INTO nr_category_format VALUES ('7','7');
INSERT INTO nr_category_format VALUES (6, 702);
INSERT INTO nr_category_format VALUES (6, 703);
INSERT INTO nr_category_format VALUES (6, 704);
INSERT INTO nr_category_format VALUES (6, 705);
INSERT INTO nr_category_format VALUES (4, 706);
INSERT INTO nr_category_format VALUES (4, 707);
INSERT INTO nr_category_format VALUES (4, 404);
INSERT INTO nr_category_format VALUES (4, 403);
INSERT INTO nr_category_format VALUES (4, 402);
INSERT INTO nr_category_format VALUES (4, 401);
INSERT INTO nr_category_format VALUES (6, 601);
INSERT INTO nr_category_format VALUES (6, 602);
INSERT INTO nr_category_format VALUES (6, 603);
INSERT INTO nr_category_format VALUES (6, 604);
INSERT INTO nr_category_format VALUES (6, 605);
INSERT INTO nr_category_format VALUES (6, 606);
INSERT INTO nr_category_format VALUES (6, 607);
INSERT INTO nr_category_format VALUES (6, 608);
INSERT INTO nr_category_format VALUES (6, 609);
INSERT INTO nr_category_format VALUES (6, 610);
INSERT INTO nr_category_format VALUES (6, 611);
INSERT INTO nr_category_format VALUES (6, 612);
INSERT INTO nr_category_format VALUES (6, 613);
INSERT INTO nr_category_format VALUES (6, 614);
INSERT INTO nr_category_format VALUES (6, 615);
INSERT INTO nr_category_format VALUES (6, 616);
INSERT INTO nr_category_format VALUES (6, 617);
INSERT INTO nr_category_format VALUES (3, 301);
INSERT INTO nr_category_format VALUES (3, 302);
INSERT INTO nr_category_format VALUES (3, 303);
INSERT INTO nr_category_format VALUES (3, 304);
INSERT INTO nr_category_format VALUES (3, 305);
INSERT INTO nr_category_format VALUES (3, 306);
INSERT INTO nr_category_format VALUES (1, 101);
INSERT INTO nr_category_format VALUES (1, 102);
INSERT INTO nr_category_format VALUES (1, 103);
INSERT INTO nr_category_format VALUES (1, 104);
INSERT INTO nr_category_format VALUES (1, 105);
INSERT INTO nr_category_format VALUES (2, 201);
INSERT INTO nr_category_format VALUES (2, 202);
INSERT INTO nr_category_format VALUES (2, 203);
INSERT INTO nr_category_format VALUES (2, 204);
INSERT INTO nr_category_format VALUES (2, 205);
INSERT INTO nr_category_format VALUES (2, 206);
INSERT INTO nr_category_format VALUES (2, 207);
INSERT INTO nr_category_format VALUES (2, 208);
INSERT INTO nr_category_format VALUES (2, 209);
INSERT INTO nr_category_format VALUES (2, 210);
INSERT INTO nr_category_format VALUES (5, 501);
INSERT INTO nr_category_format VALUES (6, 710);

-- Formatos suportados
INSERT INTO nr_format VALUES ('001','Any Text','text','any','','','n','n', 'Arquivo Texto');
INSERT INTO nr_format VALUES ('002','Any Image','image','any','','','n','n', NULL);
INSERT INTO nr_format VALUES ('003','Any Audio','audio','any','','','n','n', NULL);
INSERT INTO nr_format VALUES ('004','Any Video','video','any','','','n','n', NULL);
INSERT INTO nr_format VALUES ('005','Any Model','model','any','','','n','n', NULL);
INSERT INTO nr_format VALUES ('006','Any Application','application','any','','','n','n', NULL);
INSERT INTO nr_format VALUES ('007','Any Format','any','any','','','n','n', NULL);
INSERT INTO nr_format VALUES ('101','HTML Text','text','html','html','txt','y','n', NULL);
INSERT INTO nr_format VALUES ('102','Plain Text','text','plain','txt', 'txt','y','n', NULL);
INSERT INTO nr_format VALUES ('103','SGML Text','text','sgml','sgml','txt','y','n', NULL);
INSERT INTO nr_format VALUES ('104','WML Text','text','vnd.wap.wml','wml', 'txt','y','n', NULL);
INSERT INTO nr_format VALUES ('105','XML Text','text','xml','xml', 'txt','y','n', NULL);
INSERT INTO nr_format VALUES ('201','GIF Image','image','gif','gif', 'img','n','n', NULL);
INSERT INTO nr_format VALUES ('202','JPEG Image','image','jpeg','jpg', 'img','n','n', NULL);
INSERT INTO nr_format VALUES ('203','PNG Image','image','png','png', 'img','n','n', NULL);
INSERT INTO nr_format VALUES ('204','SVG Image','image','svg','svg', 'img','n','n', NULL);
INSERT INTO nr_format VALUES ('205','TIFF Image','image','tiff','tif', 'img','n','n', NULL);
INSERT INTO nr_format VALUES ('206','BMP Image','image','x-bmp','bmp', 'img','y','n', NULL);
INSERT INTO nr_format VALUES ('207','PSD Image','image','x-psd','psd', 'img','n','n', NULL);
INSERT INTO nr_format VALUES ('208','XBM Image','image','x-xbitmap','xbm', 'img','y','n', NULL);
INSERT INTO nr_format VALUES ('209','XCF Image','image','x-xcf','xcf', 'img','y','n', NULL);
INSERT INTO nr_format VALUES ('210','XPM Image','image','x-xpixmap','xpm', 'img','y','n', NULL);
INSERT INTO nr_format VALUES ('301','Sun/NeXT Audio','audio','basic','snd', 'aud','y','n', 'Áudio');
INSERT INTO nr_format VALUES ('302','MIDI Audio','audio','midi','mid', 'aud','y','n', 'Áudio Midi');
INSERT INTO nr_format VALUES ('303','MPEG Audio','audio','mpeg','mpa', 'aud','n','n', 'Áudio mpeg');
INSERT INTO nr_format VALUES ('304','MP3 Audio','audio','mpeg','mp3', 'aud','n','n', 'MP3');
INSERT INTO nr_format VALUES ('305','Real Audio','audio','x-realaudio','ra',  'aud','n','n', 'Real Áudio');
INSERT INTO nr_format VALUES ('306','WAV Audio','audio','x-wav','wav', 'aud','y','n', 'WAV');
INSERT INTO nr_format VALUES ('401','MPEG Video','video','mpeg','mpg','vid','n','n', 'Vídeo mpeg');
INSERT INTO nr_format VALUES ('402','QuickTime Video','video','quicktime','mov', 'vid','n','n', 'Vídeo');
INSERT INTO nr_format VALUES ('403','AVI Video','video','x-msvideo','avi', 'vid','n','n', 'Vídeo');
INSERT INTO nr_format VALUES ('404','ASF Video','video','x-ms-asf','asf', 'vid','n','n', 'Vídeo');
INSERT INTO nr_format VALUES ('501','VRML Model','model','vrml','wrl', 'mod','y','n', NULL);
INSERT INTO nr_format VALUES ('601','Word Document','application','msword','doc', 'app','y','y', 'Word');
INSERT INTO nr_format VALUES ('602','PDF Document','application','pdf','pdf', 'app','n','n', 'PDF');
INSERT INTO nr_format VALUES ('603','PostScript Document','application','postscript','ps',  'app','y','n', NULL);
INSERT INTO nr_format VALUES ('604','RTF Document','application','rtf','rtf', 'app','y','n', NULL);
INSERT INTO nr_format VALUES ('605','Excel Spreadsheet','application','vnd.ms-excel','xls', 'app','y','y', NULL);
INSERT INTO nr_format VALUES ('606','PowerPoint Presentation','application','vnd.ms-powerpoint','ppt', 'app','y','y', NULL);
INSERT INTO nr_format VALUES ('607','DVI Document','application','x-dvi','dvi', 'app','y','n', NULL);
INSERT INTO nr_format VALUES ('608','LaTeX Document','application','x-latex','tex', 'app','y','n', NULL);
INSERT INTO nr_format VALUES ('609','OGG Document','application','x-ogg','ogg', 'aud','n','n', NULL);
INSERT INTO nr_format VALUES ('610','Flash Document','application','x-shockwave-flash','swf', 'app','n','n', NULL);
INSERT INTO nr_format VALUES ('611','StarOffice Presentation','application','x-staroffice-presentation','sdd', 'app','y','n', NULL);
INSERT INTO nr_format VALUES ('612','StarOffice Spreadsheet','application','x-staroffice-spreadsheet', 'sdc', 'app','y','n', NULL);
INSERT INTO nr_format VALUES ('613','StarOffice Document','application','x-staroffice-words','sdw', 'app','y','n', NULL);
INSERT INTO nr_format VALUES ('614','TAR Archive','application','x-tar','tar', 'cmp','y','n', NULL);
INSERT INTO nr_format VALUES ('615','TeX Document','application','x-tex','tex', 'app','y','n', NULL);
INSERT INTO nr_format VALUES ('616','WordPerfect Document','application','x-wordperfect','wp6', 'app','y','n', NULL);
INSERT INTO nr_format VALUES ('617','ZIP Archive','application','x-zip','zip', 'cmp','n','n', NULL);
INSERT INTO nr_format VALUES ('702', 'Excel Spreadsheet 2007', 'application', 'vnd.openxmlformats-officedocument.spreadsheetml.sheet', 'xlsx', 'app', 'n', 'n', NULL);
INSERT INTO nr_format VALUES ('703', 'Word Document 2007', 'application', 'vnd.openxmlformats-officedocument.wordprocessingml.document', 'docx', 'app', 'n', 'n', NULL);
INSERT INTO nr_format VALUES ('704', 'PowerPoint Slideshow 2007', 'application', 'vnd.openxmlformats-officedocument.presentationml.slideshow', 'ppsx', 'app', 'n', 'n', NULL);
INSERT INTO nr_format VALUES ('705', 'PowerPoint Presentation 2007', 'application', 'vnd.openxmlformats-officedocument.presentationml.presentation', 'pptx', 'app', 'n', 'n', NULL);
INSERT INTO nr_format VALUES ('706', 'flv video', 'video', 'x-flv', 'flv', 'vid', 'n', 'n', NULL);
INSERT INTO nr_format VALUES ('707', 'MP4', 'video', 'mp4', 'mp4', 'vid', 'n', 'n', 'MP4');
INSERT INTO nr_format VALUES ('709', 'Epub Document', 'application', 'epub+zip', 'epub', 'app', 'n', 'n', 'EPUB');
INSERT INTO nr_format VALUES ('710', 'Visio Document', 'application', 'octet-stream', 'vds', NULL, 'n', 'n', 'Diagramação e Fluxogramas');
INSERT INTO nr_format VALUES ('711', 'Visio Document 2017', 'application', 'octet-stream', 'vdsx', NULL, 'n', 'n', 'Diagramação e Fluxogramas');

-- ODS (Objetivos de Desenvolvimento Sustentável)
INSERT INTO nr_ods (id, description, ordem) VALUES (14, 'ODS: 1. Erradicação da pobreza', 1);
INSERT INTO nr_ods (id, description, ordem) VALUES (17, 'ODS: 2. Erradicação da fome', 2);
INSERT INTO nr_ods (id, description, ordem) VALUES (16, 'ODS: 3. Saúde e bem-estar', 3);
INSERT INTO nr_ods (id, description, ordem) VALUES (15, 'ODS: 4. Educação de qualidade', 4);
INSERT INTO nr_ods (id, description, ordem) VALUES (7, 'ODS: 5. Igualdade de gênero', 5);
INSERT INTO nr_ods (id, description, ordem) VALUES (13, 'ODS: 6. Água potável e saneamento', 6);
INSERT INTO nr_ods (id, description, ordem) VALUES (12, 'ODS: 7. Energia acessível e limpa', 7);
INSERT INTO nr_ods (id, description, ordem) VALUES (4, 'ODS: 8. Trabalho decente e crescimento econômico', 8);
INSERT INTO nr_ods (id, description, ordem) VALUES (1, 'ODS: 9. Inovação e infraestrutura', 9);
INSERT INTO nr_ods (id, description, ordem) VALUES (11, 'ODS: 10. Redução das desigualdades', 10);
INSERT INTO nr_ods (id, description, ordem) VALUES (3, 'ODS: 11. Cidades e comunidades sustentáveis', 11);
INSERT INTO nr_ods (id, description, ordem) VALUES (6, 'ODS: 12. Consumo e produção responsáveis', 12);
INSERT INTO nr_ods (id, description, ordem) VALUES (9, 'ODS: 13. Ação contra a mudança global do clima', 13);
INSERT INTO nr_ods (id, description, ordem) VALUES (5, 'ODS: 14. Vida na água', 14);
INSERT INTO nr_ods (id, description, ordem) VALUES (8, 'ODS: 15. Vida terrestre', 15);
INSERT INTO nr_ods (id, description, ordem) VALUES (2, 'ODS: 16. Paz, justiça e instituições eficazes', 16);
INSERT INTO nr_ods (id, description, ordem) VALUES (10, 'ODS: 17. Parcerias e meios de implementação', 17);

-- Tipos de informação (68 tipos padrão do Nou-Rau)
INSERT INTO type_information (id, name) VALUES (1, 'Conferências');
INSERT INTO type_information (id, name) VALUES (2, 'Apresentações');
INSERT INTO type_information (id, name) VALUES (3, 'Colóquio');
INSERT INTO type_information (id, name) VALUES (4, 'Congressos');
INSERT INTO type_information (id, name) VALUES (5, 'Curso');
INSERT INTO type_information (id, name) VALUES (6, 'Guias');
INSERT INTO type_information (id, name) VALUES (7, 'E-books');
INSERT INTO type_information (id, name) VALUES (8, 'Encontros');
INSERT INTO type_information (id, name) VALUES (9, 'Folders');
INSERT INTO type_information (id, name) VALUES (10, 'Fóruns');
INSERT INTO type_information (id, name) VALUES (11, 'Jornadas');
INSERT INTO type_information (id, name) VALUES (12, 'Mapas');
INSERT INTO type_information (id, name) VALUES (13, 'Mesas redondas');
INSERT INTO type_information (id, name) VALUES (14, 'Painéis');
INSERT INTO type_information (id, name) VALUES (15, 'Semanas');
INSERT INTO type_information (id, name) VALUES (16, 'Seminários');
INSERT INTO type_information (id, name) VALUES (17, 'Simpósios');
INSERT INTO type_information (id, name) VALUES (18, 'Textos de discusões');
INSERT INTO type_information (id, name) VALUES (19, 'Artigos');
INSERT INTO type_information (id, name) VALUES (20, 'Artigos de Eventos');
INSERT INTO type_information (id, name) VALUES (21, 'Capítulo de livro');
INSERT INTO type_information (id, name) VALUES (22, 'Jornais');
INSERT INTO type_information (id, name) VALUES (23, 'Boletins');
INSERT INTO type_information (id, name) VALUES (24, 'Manuais');
INSERT INTO type_information (id, name) VALUES (25, 'Teses');
INSERT INTO type_information (id, name) VALUES (26, 'Relatórios');
INSERT INTO type_information (id, name) VALUES (27, 'Aula');
INSERT INTO type_information (id, name) VALUES (28, 'Periódicos');
INSERT INTO type_information (id, name) VALUES (29, 'Obras Raras');
INSERT INTO type_information (id, name) VALUES (30, 'Obras em Domínio Público');
INSERT INTO type_information (id, name) VALUES (31, 'Folhetos');
INSERT INTO type_information (id, name) VALUES (32, 'Tutoriais');
INSERT INTO type_information (id, name) VALUES (33, 'Catálogos');
INSERT INTO type_information (id, name) VALUES (34, 'Fotos');
INSERT INTO type_information (id, name) VALUES (35, 'Livros');
INSERT INTO type_information (id, name) VALUES (36, 'Objetos');
INSERT INTO type_information (id, name) VALUES (37, 'Apostilas');
INSERT INTO type_information (id, name) VALUES (38, 'Dissertações');
INSERT INTO type_information (id, name) VALUES (39, 'Memoriais docentes');
INSERT INTO type_information (id, name) VALUES (40, 'Exposições');
INSERT INTO type_information (id, name) VALUES (41, 'Leis');
INSERT INTO type_information (id, name) VALUES (42, 'Literatura geral');
INSERT INTO type_information (id, name) VALUES (43, 'Literatura infantil');
INSERT INTO type_information (id, name) VALUES (44, 'Objetos tridimensionais');
INSERT INTO type_information (id, name) VALUES (45, 'Eventos');
INSERT INTO type_information (id, name) VALUES (46, 'Workshops');
INSERT INTO type_information (id, name) VALUES (47, 'Canções escolhidas');
INSERT INTO type_information (id, name) VALUES (48, 'Parte de evento');
INSERT INTO type_information (id, name) VALUES (49, 'Microfichas');
INSERT INTO type_information (id, name) VALUES (50, 'Partituras');
INSERT INTO type_information (id, name) VALUES (51, 'Documentos técnicos administrativos');
INSERT INTO type_information (id, name) VALUES (52, 'TCCs');
INSERT INTO type_information (id, name) VALUES (53, 'Gibis');
INSERT INTO type_information (id, name) VALUES (54, 'Slides');
INSERT INTO type_information (id, name) VALUES (55, 'Vídeos');
INSERT INTO type_information (id, name) VALUES (56, 'Resumo expandido de evento');
INSERT INTO type_information (id, name) VALUES (57, 'Documentos técnicos');
INSERT INTO type_information (id, name) VALUES (58, 'Livros digitalizados');
INSERT INTO type_information (id, name) VALUES (59, 'Áudio');
INSERT INTO type_information (id, name) VALUES (60, 'Cartaz');
INSERT INTO type_information (id, name) VALUES (61, 'Sobre a Exposição');
INSERT INTO type_information (id, name) VALUES (62, 'Sobre o Evento');
INSERT INTO type_information (id, name) VALUES (63, 'Anuário');
INSERT INTO type_information (id, name) VALUES (64, 'Ficha Documental de Partitura');
INSERT INTO type_information (id, name) VALUES (65, 'Resumo');
INSERT INTO type_information (id, name) VALUES (66, 'Registro sonoro');
INSERT INTO type_information (id, name) VALUES (67, 'Projeto');

INSERT INTO nr_version (schema) VALUES ('3.0.1');
